function [data] = elvio_cycle_nedc()
% Drive cycle data for the full NEDC cycle. 
% The result has three rows:
% speed    - vehicle speed in km/h.
% duration - duration of a step in seconds.
% gear     - specified gear.
    data = [...
        elvio_cycle_ece15();...
        elvio_cycle_ece15();...
        elvio_cycle_ece15();...
        elvio_cycle_ece15();...
        elvio_cycle_eudc()];
end