function [data] = elvio_cycle_eu_nedc()
% Drive cycle data for the full NEDC cycle. 
% The result has three rows:
% speed    - vehicle speed in m/s.
% duration - duration of a step in seconds.
% gear     - specified gear.
    data = [...
        elvio_cycle_eu_ece15();...
        elvio_cycle_eu_ece15();...
        elvio_cycle_eu_ece15();...
        elvio_cycle_eu_ece15();...
        elvio_cycle_eu_eudc()];
end